-- CreateEnum
CREATE TYPE "JuniorLevel" AS ENUM ('ENTRY_LEVEL', 'LIKELY_ENTRY_LEVEL', 'AMBIGUOUS', 'EXPERIENCED', 'CLEARLY_EXPERIENCED');

-- AlterTable
ALTER TABLE "Job" ADD COLUMN     "classifiedAt" TIMESTAMPTZ(3),
ADD COLUMN     "juniorLevel" "JuniorLevel",
ADD COLUMN     "juniorScore" INTEGER,
ADD COLUMN     "requiredMaxYears" INTEGER,
ADD COLUMN     "requiredMinYears" INTEGER;

-- CreateTable
CREATE TABLE "JobClassification" (
    "id" TEXT NOT NULL,
    "jobId" TEXT NOT NULL,
    "classifierVersion" TEXT NOT NULL,
    "inputHash" TEXT NOT NULL,
    "level" "JuniorLevel" NOT NULL,
    "score" INTEGER NOT NULL,
    "minYears" INTEGER,
    "maxYears" INTEGER,
    "positiveSignals" JSONB NOT NULL,
    "negativeSignals" JSONB NOT NULL,
    "summary" TEXT,
    "isCurrent" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "JobClassification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SavedJob" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "jobId" TEXT NOT NULL,
    "note" TEXT,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SavedJob_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "JobClassification_jobId_isCurrent_idx" ON "JobClassification"("jobId", "isCurrent");

-- CreateIndex
CREATE INDEX "JobClassification_classifierVersion_createdAt_idx" ON "JobClassification"("classifierVersion", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "JobClassification_jobId_classifierVersion_inputHash_key" ON "JobClassification"("jobId", "classifierVersion", "inputHash");

-- CreateIndex
CREATE INDEX "SavedJob_userId_createdAt_idx" ON "SavedJob"("userId", "createdAt" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "SavedJob_userId_jobId_key" ON "SavedJob"("userId", "jobId");

-- CreateIndex
CREATE INDEX "Job_juniorLevel_effectivePostedAt_idx" ON "Job"("juniorLevel", "effectivePostedAt" DESC);

-- CreateIndex
CREATE INDEX "Job_juniorScore_effectivePostedAt_idx" ON "Job"("juniorScore" DESC, "effectivePostedAt" DESC);

-- AddForeignKey
ALTER TABLE "JobClassification" ADD CONSTRAINT "JobClassification_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SavedJob" ADD CONSTRAINT "SavedJob_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SavedJob" ADD CONSTRAINT "SavedJob_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Hand-written, not generated by Prisma: Prisma's schema language has no partial
-- unique index (docs/DATABASE.md §5). Enforces the §3.5 invariant that exactly one
-- classification per job carries isCurrent, so the job detail page and the
-- denormalized block on "Job" always have a single unambiguous source. It also
-- serves the detail fetch (§7). The rest of §5's raw SQL belongs to M2.6.
CREATE UNIQUE INDEX "JobClassification_one_current_idx"
  ON "JobClassification" ("jobId") WHERE "isCurrent";
