// M2.7 — development seed (docs/MILESTONES.md M2.7).
//
//   npm run db:seed          (from backend/, loads backend/.env via the Prisma CLI)
//
// Writes a demo user, a demo admin, two fixture sources, and the fixture job set
// in `seed-data.ts` with one classification each. It exists so the API and the
// frontend are developable before ingestion is built (docs/ARCHITECTURE.md §12).
//
// IDEMPOTENT BY CONSTRUCTION. Every write is an upsert on a natural key that the
// schema already enforces as unique, so re-running mutates rows instead of adding
// them and row counts do not move:
//
//   User               email
//   Profile            userId
//   JobSource          key
//   Job                dedupHash                       (D1)
//   JobPosting         (sourceId, externalId)          (dedup tier 1)
//   JobClassification  (jobId, classifierVersion, inputHash)
//   SavedJob           (userId, jobId)
//
// It never deletes. A fixture removed from `seed-data.ts` stays in the database
// until the developer resets it — the seed adds and updates, nothing else.
//
// It also never writes `Job.searchVector`: that column is generated by PostgreSQL
// from title/companyName/description under the row's language configuration
// (docs/DATABASE.md §5.1). A direct write is rejected by the database.
//
// NOTE FOR ANYONE VERIFYING SEARCH WITH THIS DATA: a bulk load leaves the GIN
// entries in the pending list, so an EXPLAIN straight after seeding can show a
// sequential scan even though the indexes are healthy. Run VACUUM ANALYZE first.
// This bit M2.6's verification; see its notes in docs/MILESTONES.md.

import 'reflect-metadata'; // PasswordHasherService is a decorated Nest provider

import { createHash } from 'node:crypto';
import { PrismaClient, type Prisma } from '@prisma/client';

import { PasswordHasherService } from '../src/modules/auth/password-hasher.service';
import {
  DEMO_ADMIN,
  DEMO_SAVED_JOB_REFS,
  DEMO_USER,
  SEED_JOBS,
  SEED_SOURCES,
  type SeedJob,
} from './seed-data';

const prisma = new PrismaClient();
const hasher = new PasswordHasherService();

/**
 * Marks the classifications this seed writes. Deliberately not "rules-1.0" or
 * "llm-1.0" (docs/DATABASE.md §3.5): no classifier exists yet, and labelling
 * hand-written fixtures as a classifier's output would corrupt the offline
 * evaluation that `(classifierVersion, createdAt)` is indexed for.
 */
const SEED_CLASSIFIER_VERSION = 'seed-fixture-1.0';

const sha256 = (value: string): string =>
  createHash('sha256').update(value, 'utf8').digest('hex');

/** D1 / docs/ARCHITECTURE.md §6.3 — the one dedup rule the seed applies itself. */
const dedupHashOf = (job: SeedJob): string =>
  sha256(`${job.companySlug}|${job.normalizedTitle}|${job.countryCode ?? ''}`);

/** Stands in for the normalized posting payload; ingestion uses it to skip re-classification. */
const contentHashOf = (job: SeedJob): string =>
  sha256(`${job.title}\n${job.description}`);

/** The text a classifier consumed. Doubles as the classification cache key (§3.5). */
const inputHashOf = (job: SeedJob): string => sha256(job.description);

// One run timestamp for the whole seed, so every relative date in a single run
// shares an origin and the ordering between fixtures is exactly as written.
const RUN_AT = new Date();
const daysAgo = (days: number): Date =>
  new Date(RUN_AT.getTime() - days * 24 * 60 * 60 * 1000);

async function seedSources(): Promise<Map<string, string>> {
  const idsByKey = new Map<string, string>();

  for (const source of SEED_SOURCES) {
    const { key, ...fields } = source;
    const row = await prisma.jobSource.upsert({
      where: { key },
      create: { key, ...fields },
      update: fields,
      select: { id: true },
    });
    idsByKey.set(key, row.id);
  }

  return idsByKey;
}

async function seedUsers(): Promise<{ demoUserId: string }> {
  const [demoHash, adminHash] = await Promise.all([
    hasher.hash(DEMO_USER.password),
    hasher.hash(DEMO_ADMIN.password),
  ]);

  // The hash is only written on create: re-seeding must not invalidate a
  // password a developer has deliberately changed, and re-hashing on every run
  // would churn the row for no reason.
  const demoUser = await prisma.user.upsert({
    where: { email: DEMO_USER.email },
    create: { email: DEMO_USER.email, passwordHash: demoHash, role: 'USER' },
    update: {},
    select: { id: true },
  });

  await prisma.user.upsert({
    where: { email: DEMO_ADMIN.email },
    create: { email: DEMO_ADMIN.email, passwordHash: adminHash, role: 'ADMIN' },
    update: { role: 'ADMIN' },
  });

  const profile = {
    displayName: DEMO_USER.displayName,
    yearsOfExperience: DEMO_USER.yearsOfExperience,
    desiredRoles: DEMO_USER.desiredRoles,
    technologies: DEMO_USER.technologies,
    locations: DEMO_USER.locations,
    countryCodes: DEMO_USER.countryCodes,
    workplaceTypes: DEMO_USER.workplaceTypes,
  };

  await prisma.profile.upsert({
    where: { userId: demoUser.id },
    create: { userId: demoUser.id, ...profile },
    update: profile,
  });

  return { demoUserId: demoUser.id };
}

async function seedJob(job: SeedJob): Promise<string> {
  const postedAt =
    job.postedDaysAgo === null ? null : daysAgo(job.postedDaysAgo);

  const fields = {
    title: job.title,
    normalizedTitle: job.normalizedTitle,
    companyName: job.companyName,
    companySlug: job.companySlug,
    location: job.location,
    countryCode: job.countryCode,
    workplaceType: job.workplaceType,
    employmentType: job.employmentType,
    language: job.language,
    description: job.description,
    technologies: job.technologies,
    postedAt,
    // Non-null by design (§3.3): coalesce onto the observation date so sorting
    // and pagination stay stable for sources that publish no date.
    effectivePostedAt: postedAt ?? RUN_AT,
    isActive: job.isActive,
    // Denormalized from the classification below so search filters and sorts
    // without a join. Kept in step with it by writing both from one fixture.
    juniorLevel: job.classification.level,
    juniorScore: job.classification.score,
    requiredMinYears: job.classification.minYears,
    requiredMaxYears: job.classification.maxYears,
    classifiedAt: RUN_AT,
  } satisfies Omit<Prisma.JobUncheckedCreateInput, 'dedupHash'>;

  // mergedIntoJobId is set in a second pass: the target job may not exist yet.
  const row = await prisma.job.upsert({
    where: { dedupHash: dedupHashOf(job) },
    create: { dedupHash: dedupHashOf(job), ...fields },
    // lastSeenAt is written explicitly, never @updatedAt — an unrelated write
    // must not make a stale job look freshly observed (§3.3, §8).
    update: { ...fields, lastSeenAt: RUN_AT },
    select: { id: true },
  });

  return row.id;
}

async function seedPostings(
  job: SeedJob,
  jobId: string,
  sourceIds: Map<string, string>,
): Promise<void> {
  const postedAt =
    job.postedDaysAgo === null ? null : daysAgo(job.postedDaysAgo);

  for (const posting of job.postings) {
    const sourceId = sourceIds.get(posting.sourceKey);
    if (!sourceId) {
      throw new Error(
        `Fixture "${job.ref}" references unknown source "${posting.sourceKey}"`,
      );
    }

    const fields = {
      jobId,
      url: posting.url,
      title: job.title,
      companyName: job.companyName,
      companySlug: job.companySlug,
      location: job.location,
      countryCode: job.countryCode,
      workplaceType: job.workplaceType,
      employmentType: job.employmentType,
      language: job.language,
      description: job.description,
      contentHash: contentHashOf(job),
      technologies: job.technologies,
      postedAt,
      isActive: job.isActive,
    };

    await prisma.jobPosting.upsert({
      where: {
        sourceId_externalId: { sourceId, externalId: posting.externalId },
      },
      create: { sourceId, externalId: posting.externalId, ...fields },
      update: { ...fields, lastSeenAt: RUN_AT },
    });
  }
}

async function seedClassification(job: SeedJob, jobId: string): Promise<void> {
  const inputHash = inputHashOf(job);
  const {
    level,
    score,
    minYears,
    maxYears,
    positiveSignals,
    negativeSignals,
    summary,
  } = job.classification;

  // Exactly one row per job may carry isCurrent (partial unique index, §5). If a
  // fixture's description was edited since the last run its inputHash changed, so
  // stand the previous row down *before* writing the new one or the insert
  // collides with the index rather than replacing the row.
  await prisma.jobClassification.updateMany({
    where: { jobId, isCurrent: true, NOT: { inputHash } },
    data: { isCurrent: false },
  });

  const fields = {
    level,
    score,
    minYears,
    maxYears,
    positiveSignals: positiveSignals as unknown as Prisma.InputJsonValue,
    negativeSignals: negativeSignals as unknown as Prisma.InputJsonValue,
    summary,
    isCurrent: true,
  };

  await prisma.jobClassification.upsert({
    where: {
      jobId_classifierVersion_inputHash: {
        jobId,
        classifierVersion: SEED_CLASSIFIER_VERSION,
        inputHash,
      },
    },
    create: {
      jobId,
      classifierVersion: SEED_CLASSIFIER_VERSION,
      inputHash,
      ...fields,
    },
    update: fields,
  });
}

async function seedSavedJobs(
  demoUserId: string,
  jobIds: Map<string, string>,
): Promise<void> {
  for (const ref of DEMO_SAVED_JOB_REFS) {
    const jobId = jobIds.get(ref);
    if (!jobId) {
      throw new Error(
        `DEMO_SAVED_JOB_REFS references unknown fixture "${ref}"`,
      );
    }

    await prisma.savedJob.upsert({
      where: { userId_jobId: { userId: demoUserId, jobId } },
      create: { userId: demoUserId, jobId },
      update: {},
    });
  }
}

async function main(): Promise<void> {
  const sourceIds = await seedSources();
  const { demoUserId } = await seedUsers();

  const jobIds = new Map<string, string>();
  for (const job of SEED_JOBS) {
    jobIds.set(job.ref, await seedJob(job));
  }

  // Second pass — every job now exists, so merge redirects can be resolved (D2).
  for (const job of SEED_JOBS) {
    if (!job.mergedIntoRef) continue;

    const target = jobIds.get(job.mergedIntoRef);
    if (!target) {
      throw new Error(
        `Fixture "${job.ref}" merges into unknown fixture "${job.mergedIntoRef}"`,
      );
    }

    await prisma.job.update({
      where: { id: jobIds.get(job.ref) },
      data: { mergedIntoJobId: target },
    });
  }

  for (const job of SEED_JOBS) {
    const jobId = jobIds.get(job.ref)!;
    await seedPostings(job, jobId, sourceIds);
    await seedClassification(job, jobId);
  }

  await seedSavedJobs(demoUserId, jobIds);

  const [sources, users, profiles, jobs, postings, classifications, savedJobs] =
    await Promise.all([
      prisma.jobSource.count(),
      prisma.user.count(),
      prisma.profile.count(),
      prisma.job.count(),
      prisma.jobPosting.count(),
      prisma.jobClassification.count(),
      prisma.savedJob.count(),
    ]);

  console.log('Seed complete. Row counts:');
  console.table({
    JobSource: sources,
    User: users,
    Profile: profiles,
    Job: jobs,
    JobPosting: postings,
    JobClassification: classifications,
    SavedJob: savedJobs,
  });
  console.log(
    `\nDemo user:  ${DEMO_USER.email} / ${DEMO_USER.password}` +
      `\nDemo admin: ${DEMO_ADMIN.email} / ${DEMO_ADMIN.password}` +
      '\nDevelopment credentials only — these fixtures must never be seeded into production.',
  );
}

main()
  .catch((error: unknown) => {
    console.error('Seed failed:', error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
